image:
  repository: eqalpha/keydb
  tag: alpine_x86_64_v6.3.4
  pullPolicy: IfNotPresent

service:
  port: 6379

persistence:
  enabled: true
  storageClass: 
  accessModes: ReadWriteOnce
  size: 100Mi

config: |
  active-replica yes
  multi-master no
  maxmemory 200mb
  maxmemory-policy allkeys-lru
  appendonly yes
  port 6379
  protected-mode no

replicas: 3

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

haproxy:
  image: haproxy
  tag: latest
  pullPolicy: IfNotPresent
  replicas: 2
  configTemplate: |
    global
        log stdout format raw local0

    defaults
        log global
        mode tcp
        option tcplog
        timeout connect 5s
        timeout client 30s
        timeout server 30s

    frontend fe_keydb
        bind *:6379
        default_backend be_keydb

    backend be_keydb
