replicaCount: 3

image:
  repository: eqalpha/keydb
  tag: "alpine_x86_64_v6.3.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 100Mi

config: |
  active-replica yes
  multi-master no
  maxmemory 200mb
  maxmemory-policy allkeys-lru
