image:
  repository: eqalpha/keydb
  tag: "alpine_x86_64_v6.3.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

persistence:
  enabled: true
  storageClass: "longhorn"
  accessModes:
    - ReadWriteOnce
  size: 100Mi

configs:
  - |
    active-replica yes
    multi-master no
    maxmemory 200mb
    maxmemory-policy allkeys-lru
    replicaof keydb-replica-1
    replicaof keydb-replica-2
  - |
    active-replica yes
    multi-master no
    maxmemory 200mb
    maxmemory-policy allkeys-lru
    replicaof keydb-replica-0
    replicaof keydb-replica-2
  - |
    active-replica yes
    multi-master no
    maxmemory 200mb
    maxmemory-policy allkeys-lru
    replicaof keydb-replica-1
    replicaof keydb-replica-0
