image:
  repository: eqalpha/keydb
  tag: "alpine_x86_64_v6.3.4"
  pullPolicy: IfNotPresent

service:
  port: 6379

persistence:
  enabled: true
  storageClass: 
  accessModes: ReadWriteOnce
  size: 100Mi

config: |
  active-replica yes
  multi-master no
  maxmemory 200mb
  maxmemory-policy allkeys-lru
  appendonly yes
  port 6379
  protected-mode no

replicas: 3

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
