apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-haproxy-utils
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
data:
  haproxy-config.sh: |
    #!/bin/sh
    set -euxo

    host="$(hostname)"
    replicas=""
    node=0
    while [ $node -lt {{ .Values.replicas | int }} ]; do
      if [ $node -eq 0 ]; then
        replicas="${replicas}    server {{ .Release.Name }}-${node}.{{ .Release.Name }}-headless:{{ .Values.service.port }} check\n"
      else
        replicas="${replicas}    server {{ .Release.Name }}-${node}.{{ .Release.Name }}-headless:{{ .Values.service.port }} check backup\n"
      fi
      node=$((node + 1))
    done

    cat <<EOF > /tmp/haproxy.cfg
    {{ .Values.haproxy.configTemplate | nindent 4 }}
    ${replicas}
    EOF

    exec haproxy -f /tmp/haproxy.cfg
