apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-haproxy
  labels:
    app: {{ .Release.Name }}-haproxy
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-haproxy
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
