apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keydb.fullname" . }}-utils
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
type: Opaque
stringData:
  server.sh: |
    #!/bin/sh
    set -euxo pipefail

    host="$(hostname)"
    replicas=""
    namespace="$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)"
    node=0
    while [ $node -lt {{ .Values.nodes | int }} ]; do
      if [ "${host}" != "{{ include "keydb.fullname" . }}-${node}" ]; then
        replicas="${replicas}replicaof {{ include "keydb.fullname" . }}-${node}.{{ include "keydb.fullname" . }} {{ .Values.service.port }}\n"
      fi
      node=$((node + 1))
    done

    cat <<EOF > /etc/keydb/redis.conf
    {{ .Values.config | nindent 4 }}
    EOF

    echo -e "${replicas}" >> /etc/keydb/redis.conf
    exec keydb-server /etc/keydb/redis.conf
