apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-utils
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
type: Opaque
stringData:
  server.sh: |
    #!/bin/sh
    set -euxo pipefail

    host="$(hostname)"
    replicas=""
    node=0
    while [ $node -lt {{ .Values.nodes | int }} ]; do
      if [ "${host}" != "{{ .Release.Name }}-${node}" ]; then
        replicas="${replicas}replicaof {{ .Release.Name }}-${node}.{{ .Release.Name }}-headless {{ .Values.service.port }}\n"
      fi
      node=$((node + 1))
    done

    cat <<EOF > /etc/keydb/keydb.conf
    {{ .Values.config | nindent 4 }}
    EOF

    echo -e "${replicas}" >> /etc/keydb/keydb.conf
    exec keydb-server /etc/keydb/keydb.conf
