apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keydb-replicas
spec:
  serviceName: keydb-service
  replicas: {{ .Values.replicaCount | int }}
  selector:
    matchLabels:
      app: keydb-replica
  template:
    metadata:
      labels:
        app: keydb-replica
    spec:
      containers:
        - name: keydb-replica
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: keydb-storage
              mountPath: /data
            - name: config-volume
              mountPath: /etc/keydb/keydb.conf
              subPath: keydb.conf
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - "keydb-server"
            - "/etc/keydb/keydb.conf"
      volumes:
        - name: config-volume
          configMap:
            name: keydb-configmap
  volumeClaimTemplates:
    - metadata:
        name: keydb-storage
      spec:
        accessModes: 
          {{ .Values.persistence.accessModes | toYaml | indent 8 }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
