apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keydb
  labels:
    app: keydb
spec:
  serviceName: keydb
  replicas: {{ .Values.configs | len }}
  selector:
    matchLabels:
      app: keydb
  template:
    metadata:
      labels:
        app: keydb
    spec:
      containers:
        - name: keydb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["keydb-server", "/etc/keydb/keydb.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: config-volume
              mountPath: /etc/keydb
            - name: data
              mountPath: /data
      volumes:
        - name: config-volume
          configMap:
            name: keydb-config-{{ $index }}
        - name: data
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
