apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keydb-replica
  labels:
    app: keydb-replica
spec:
  serviceName: keydb-service
  replicas: {{ .Values.replicaCount | int }}
  selector:
    matchLabels:
      app: keydb-replica
  template:
    metadata:
      labels:
        app: keydb-replica
    spec:
      initContainers:
        - name: setup-replication
          image: busybox
          command:
            - /bin/sh
            - -c
          args:
            - |
              echo "Starting replication setup"
              POD_NAME=$(hostname)
              FULL_NAME="keydb-replica-${POD_NAME##*-}"
              ALL_REPLICAS=$(for i in $(seq 0 $(( {{ .Values.replicaCount }} - 1 )) ); do if [ "$FULL_NAME" != "keydb-replica-$i" ]; then echo "keydb-replica-$i 6379"; fi; done)
              echo $ALL_REPLICAS > /replicas/replica-hosts
          volumeMounts:
            - name: replicas
              mountPath: /replicas
      containers:
        - name: keydb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: keydb-storage
              mountPath: /data
            - name: config-volume
              mountPath: /etc/keydb/keydb.conf
              subPath: keydb.conf
            - name: replicas
              mountPath: /replicas
          args:
            - "sh"
            - "-c"
            - |
              keydb-server /etc/keydb/keydb.conf &
              sleep 10
              for host in $(cat /replicas/replica-hosts); do
                keydb-cli --replicaof $host
              done
              wait
      volumes:
        - name: config-volume
          configMap:
            name: keydb-configmap
        - name: replicas
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: keydb-storage
      spec:
        accessModes: 
          {{ .Values.persistence.accessModes | toYaml | indent 8 }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
