apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keydb-replica
  labels:
    app: keydb-replica
spec:
  serviceName: keydb-service
  replicas: {{ .Values.replicaCount | int }}
  selector:
    matchLabels:
      app: keydb-replica
  template:
    metadata:
      labels:
        app: keydb-replica
    spec:
      initContainers:
        - name: setup-replication
          image: busybox
          command:
            - /bin/sh
            - -c
          args:
            - |
              echo "Starting replication setup" > /tmp/debug.log
              POD_NAME=$(hostname)
              FULL_NAME="keydb-replica-${POD_NAME##*-}"
              echo "Pod name: $POD_NAME, Full name: $FULL_NAME" >> /tmp/debug.log
              ALL_REPLICAS=$(for i in $(seq 0 $(( {{ .Values.replicaCount }} - 1 )) ); do if [ "$FULL_NAME" != "keydb-replica-$i" ]; then echo "replicaof keydb-replica-$i 6379"; fi; done)
              echo "All replicas: $ALL_REPLICAS" >> /tmp/debug.log
              echo $ALL_REPLICAS >> /etc/keydb/keydb.conf
              echo "Contents of keydb.conf:" >> /tmp/debug.log
              cat /etc/keydb/keydb.conf >> /tmp/debug.log
              cat /tmp/debug.log
          volumeMounts:
            - name: config-volume
              mountPath: /etc/keydb
            - name: debug-volume
              mountPath: /tmp
      containers:
        - name: keydb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: keydb-storage
              mountPath: /data
            - name: config-volume
              mountPath: /etc/keydb
            - name: debug-volume
              mountPath: /tmp
          args:
            - "keydb-server"
            - "/etc/keydb/keydb.conf"
      volumes:
        - name: config-volume
          configMap:
            name: keydb-configmap
        - name: keydb-storage
          emptyDir: {}
        - name: debug-volume
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: keydb-storage
      spec:
        accessModes: 
          {{ .Values.persistence.accessModes | toYaml | indent 8 }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
