apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keydb
  labels:
    app: keydb
spec:
  serviceName: keydb
  replicas: {{ .Values.configs | len }}
  selector:
    matchLabels:
      app: keydb
  template:
    metadata:
      labels:
        app: keydb
    spec:
      initContainers:
        - name: setup-config
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              POD_NAME=$(hostname)
              POD_INDEX=$(echo $POD_NAME | awk -F "-" '{print $NF}')
              CONFIG_DIR="/etc/keydb/configs"
              mkdir -p $CONFIG_DIR
              echo "${CONFIGS[$POD_INDEX]}" > $CONFIG_DIR/keydb.conf
          env:
            - name: CONFIGS
              value: |
                {{- range .Values.configs }}
                {{ . | nindent 16 }}
                {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/keydb/configs
      containers:
        - name: keydb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["keydb-server", "/etc/keydb/configs/keydb.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: config-volume
              mountPath: /etc/keydb/configs
            - name: data
              mountPath: /data
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: data
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: 
          {{ .Values.persistence.accessModes | toYaml | indent 8 }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
