apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include ".Release.Name" . }}
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include ".Release.Name" . }}-headless
  replicas: {{ .Values.nodes }}
  selector:
    matchLabels:
      app: {{ include ".Release.Name" . }}
  template:
    metadata:
      labels:
        app: {{ include ".Release.Name" . }}
    spec:
      containers:
        - name: keydb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh", "/etc/keydb-utils/server.sh"]
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: utils
              mountPath: /utils
              readOnly: true
            - name: data
              mountPath: /data
      volumes:
        - name: utils
          secret:
            secretName: {{ include ".Release.Name" . }}-utils
        - name: data
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.persistence.accessModes }}
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
